"""create reports table

Revision ID: bdc239d0a555
Revises: efa33bccf5b7
Create Date: 2026-07-20 22:06:56.875803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc239d0a555'
down_revision = 'efa33bccf5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_product_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('\n            (\n                target_user_id IS NOT NULL\n                AND target_product_id IS NULL\n            )\n            OR\n            (\n                target_user_id IS NULL\n                AND target_product_id IS NOT NULL\n            )\n            ', name='ck_reports_exactly_one_target'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'target_product_id', name='uq_reports_reporter_product'),
    sa.UniqueConstraint('reporter_id', 'target_user_id', name='uq_reports_reporter_user')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_product_id'), ['target_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_user_id'), ['target_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_target_product_id'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
