"""create transfers table

Revision ID: d689a2fe4829
Revises: bdc239d0a555
Create Date: 2026-07-20 22:38:27.669235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd689a2fe4829'
down_revision = 'bdc239d0a555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount BETWEEN 1 AND 1000000', name='ck_transfers_amount_range'),
    sa.CheckConstraint('sender_id != recipient_id', name='ck_transfers_different_users'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_sender_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_recipient_id'))

    op.drop_table('transfers')
    # ### end Alembic commands ###
